version: '2'
services:
  mysql:
    build: mysql
    environment:
      # MYSQL pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: php
    ports:
      - '80:80'
    volumes:
      # Apacheのドキュメントルート
      - ./htdocs:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
