version: '2'
services:
  mysql:
    build: mysql
    environment:
      # MYSQL pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
      # sql/ 以下の sql を初期データとして を読み込む (コメントアウト外す)
#      - ./sql:/docker-entrypoint-initdb.d
  php:
    build: php
    ports:
      # 0.0.0.0 / localhost
      - '80:80'
    volumes:
      # Apacheのドキュメントルート
      - ./htdocs:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
